using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using Microsoft.Win32;
using NetworkHelper.Data;
using NetworkHelper.Dialogs;
using NetworkHelper.Domain;
using NetworkHelper.Ingestion;
using NetworkHelper.Services;

namespace NetworkHelper;

public partial class MainWindow : Window
{
    private Database _db=null!; private readonly TabularImporter _reader=new(); private readonly VisioImporter _visioReader=new(); private ImportService _imports=null!; private VisioImportService _visioImports=null!; private RelationshipInferenceService _relationshipInference=null!; private TroubleshootingAdvisorService _troubleshooter=null!; private DeviceTraversalService _traversal=null!; private TopologyGraphService _topology=null!; private readonly PathfindingService _pathfinder=new(); private readonly HashSet<long> _troubleUnavailableRelationships=[]; private string? _pendingPath; private List<ImportRow> _preview=[]; private List<VisioProposal> _visioPreview=[]; private long? _activeTroubleSessionId;private double _topologyZoom=1;
    private List<Device> _siteDevices=[]; private List<NetworkRecord> _siteNetworks=[]; private bool _updatingFilters;
    private Company? Company=>CompaniesList.SelectedItem as Company; private Site? Site=>SitesList.SelectedItem as Site;
    public MainWindow() { InitializeComponent(); try { _db=new Database(); _db.Initialize(); _imports=new ImportService(_db); _visioImports=new VisioImportService(_db); _relationshipInference=new RelationshipInferenceService(_db); _troubleshooter=new TroubleshootingAdvisorService(_db,_pathfinder);_traversal=new DeviceTraversalService(_db);_topology=new TopologyGraphService(_db);CommandMemoryGrid.ItemsSource=_db.Commands(); ReloadCompanies(); } catch(Exception ex) { MessageBox.Show($"Could not open the local database.\n\n{ex.Message}","Network Helper",MessageBoxButton.OK,MessageBoxImage.Error); Loaded+=(_,_)=>Close(); } }
    private void ReloadCompanies(long? select=null) { CompaniesList.ItemsSource=_db.Companies(); if(select.HasValue) CompaniesList.SelectedItem=((IEnumerable<Company>)CompaniesList.ItemsSource).FirstOrDefault(x=>x.Id==select); }
    private void ReloadSites(long? select=null) { var sites=Company is null?[]:_db.Sites(Company.Id); SitesList.ItemsSource=sites; if(select.HasValue)SitesList.SelectedItem=sites.FirstOrDefault(x=>x.Id==select); }
    private void RefreshSite()
    {
        var s=Site; SiteTitle.Text=s?.Name??(Company is null?"Select a company":"Company workspace"); SiteSubtitle.Text=s is null?(Company is null?"":"Import company data or select a site."):string.IsNullOrWhiteSpace(s.Address)?$"{Company?.Name}  /  Site inventory":s.Address; Tabs.IsEnabled=Company is not null;
        if(s is null){_siteDevices=[];_siteNetworks=[];DevicesGrid.ItemsSource=NetworksGrid.ItemsSource=SourcesGrid.ItemsSource=ConflictsGrid.ItemsSource=RelationshipsGrid.ItemsSource=RelationshipDeviceBox.ItemsSource=TroubleTargetBox.ItemsSource=TroubleSessionsGrid.ItemsSource=TroubleStepsGrid.ItemsSource=TroubleTraversalGrid.ItemsSource=TopologyRootBox.ItemsSource=TopologyTargetBox.ItemsSource=null;TopologyCanvas.Children.Clear();DeviceCountText.Text=NetworkCountText.Text=ConflictCountText.Text="0";TroubleSummaryText.Text="Select a site to begin a local investigation.";TraversalSummaryText.Text="Select a site and target device to build a traversal.";TopologySummaryText.Text="Select a site and firewall, then build the topology.";return;}
        var selectedRelationshipDevice=(RelationshipDeviceBox.SelectedItem as Device)?.Id;var selectedTroubleDevice=(TroubleTargetBox.SelectedItem as Device)?.Id;var selectedTopologyRoot=(TopologyRootBox.SelectedItem as Device)?.Id;var selectedTopologyTarget=(TopologyTargetBox.SelectedItem as Device)?.Id;_siteDevices=_db.Devices(s.Id); _siteNetworks=_db.Networks(s.Id); var conflicts=_db.Conflicts(s.Id); PopulateFilters(); ApplyDeviceFilters(); ApplyNetworkFilters();RelationshipDeviceBox.ItemsSource=_siteDevices;RelationshipDeviceBox.SelectedItem=_siteDevices.FirstOrDefault(x=>x.Id==selectedRelationshipDevice)??_siteDevices.FirstOrDefault();TroubleTargetBox.ItemsSource=_siteDevices;TroubleTargetBox.SelectedItem=_siteDevices.FirstOrDefault(x=>x.Id==selectedTroubleDevice);var topologyRoots=_siteDevices.Where(x=>x.DeviceType?.Equals("Firewall",StringComparison.OrdinalIgnoreCase)==true).OrderBy(x=>x.Name).ToList();if(topologyRoots.Count==0)topologyRoots=_siteDevices.Where(x=>x.DeviceType?.Equals("Router",StringComparison.OrdinalIgnoreCase)==true).OrderBy(x=>x.Name).ToList();TopologyRootBox.ItemsSource=topologyRoots;TopologyRootBox.SelectedItem=topologyRoots.FirstOrDefault(x=>x.Id==selectedTopologyRoot)??topologyRoots.FirstOrDefault();TopologyTargetBox.ItemsSource=_siteDevices.OrderBy(x=>x.Name).ToList();TopologyTargetBox.SelectedItem=_siteDevices.FirstOrDefault(x=>x.Id==selectedTopologyTarget);TroubleSessionsGrid.ItemsSource=_db.TroubleshootingSessions(s.Id);RefreshRelationships(); SourcesGrid.ItemsSource=_db.Sources(s.Id).Select(x=>new{File=x.File,Type=x.Type,Imported=x.Imported}); ConflictsGrid.ItemsSource=conflicts;
        var unresolved=conflicts.Count(x=>x.Status=="unresolved");DeviceCountText.Text=_siteDevices.Count.ToString();NetworkCountText.Text=_siteNetworks.Count.ToString();ConflictCountText.Text=unresolved.ToString();OverviewText.Text=$"Database\n{_db.StoragePath}\n\nAll inventory and source evidence stays on this computer. Network Helper makes no network requests and stores no credentials.";RenderTopology();
    }
    private void PopulateFilters(){_updatingFilters=true;var selectedType=DeviceTypeFilter.SelectedItem as string??"All types";var selectedDeviceZone=DeviceZoneFilter.SelectedItem as string??"All zones";var selectedNetworkZone=NetworkZoneFilter.SelectedItem as string??"All zones";DeviceTypeFilter.ItemsSource=new[]{"All types"}.Concat(_siteDevices.Select(x=>x.DeviceType).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(x=>x)).ToList();DeviceZoneFilter.ItemsSource=new[]{"All zones"}.Concat(_siteDevices.Select(x=>x.Zone).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(x=>x)).ToList();NetworkZoneFilter.ItemsSource=new[]{"All zones"}.Concat(_siteNetworks.Select(x=>x.Zone).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(x=>x)).ToList();DeviceTypeFilter.SelectedItem=DeviceTypeFilter.Items.Contains(selectedType)?selectedType:"All types";DeviceZoneFilter.SelectedItem=DeviceZoneFilter.Items.Contains(selectedDeviceZone)?selectedDeviceZone:"All zones";NetworkZoneFilter.SelectedItem=NetworkZoneFilter.Items.Contains(selectedNetworkZone)?selectedNetworkZone:"All zones";_updatingFilters=false;}
    private void ApplyDeviceFilters(){if(_updatingFilters||DevicesGrid is null)return;var q=DeviceSearchBox?.Text?.Trim()??"";var type=DeviceTypeFilter?.SelectedItem as string;var zone=DeviceZoneFilter?.SelectedItem as string;DevicesGrid.ItemsSource=_siteDevices.Where(x=>(string.IsNullOrWhiteSpace(q)||new[]{x.Name,x.IpAddress,x.Model,x.Vendor,x.Description,x.DeviceType,x.Zone}.Any(v=>v?.Contains(q,StringComparison.OrdinalIgnoreCase)==true))&&(type is null or "All types"||string.Equals(x.DeviceType,type,StringComparison.OrdinalIgnoreCase))&&(zone is null or "All zones"||string.Equals(x.Zone,zone,StringComparison.OrdinalIgnoreCase))).ToList();}
    private void ApplyNetworkFilters(){if(_updatingFilters||NetworksGrid is null)return;var q=NetworkSearchBox?.Text?.Trim()??"";var zone=NetworkZoneFilter?.SelectedItem as string;NetworksGrid.ItemsSource=_siteNetworks.Where(x=>(string.IsNullOrWhiteSpace(q)||new[]{x.Name,x.Cidr,x.VlanId?.ToString(),x.Zone}.Any(v=>v?.Contains(q,StringComparison.OrdinalIgnoreCase)==true))&&(zone is null or "All zones"||string.Equals(x.Zone,zone,StringComparison.OrdinalIgnoreCase))).ToList();}
    private void DeviceFilter_Changed(object sender,RoutedEventArgs e)=>ApplyDeviceFilters();
    private void NetworkFilter_Changed(object sender,RoutedEventArgs e)=>ApplyNetworkFilters();
    private void RefreshRelationships(){if(Site is not{ } site)return;var device=RelationshipDeviceBox.SelectedItem as Device;RelationshipsGrid.ItemsSource=_db.Relationships(site.Id,device?.Id);PathResultsList.ItemsSource=null;}
    private void DevicesGrid_SelectionChanged(object sender,System.Windows.Controls.SelectionChangedEventArgs e){if(DevicesGrid.SelectedItem is Device selected&&RelationshipDeviceBox is not null)RelationshipDeviceBox.SelectedItem=_siteDevices.FirstOrDefault(x=>x.Id==selected.Id);}
    private void RelationshipDevice_Changed(object sender,System.Windows.Controls.SelectionChangedEventArgs e)=>RefreshRelationships();
    private void InferRelationships_Click(object sender,RoutedEventArgs e){if(Site is not{ } site)return;try{var added=_relationshipInference.Infer(site.Id);RefreshRelationships();MessageBox.Show(this,$"Inference complete. {added} new supported relationship(s) added.","Relationships");}catch(Exception ex){MessageBox.Show(this,$"Relationship inference failed.\n\n{ex.Message}");}}
    private void AddRelationship_Click(object sender,RoutedEventArgs e){if(Site is not{ } site)return;var target=RelationshipDeviceBox.SelectedItem as Device;var dialog=new RelationshipDialog(target?.Name){Owner=this};if(dialog.ShowDialog()!=true)return;var entities=_db.Entities(site.Id);EntityRef Resolve(string name)=>entities.FirstOrDefault(x=>x.Name.Equals(name,StringComparison.OrdinalIgnoreCase))??new("access_node",null,name);try{_db.AddRelationship(site.Id,Resolve(dialog.FromName),Resolve(dialog.ToName),dialog.RelationshipType,1,"confirmed",dialog.Basis??"Manually documented relationship",dialog.ScopeKey);RefreshRelationships();}catch(Exception ex){MessageBox.Show(this,$"Could not add relationship.\n\n{ex.Message}");}}
    private void ConfirmRelationship_Click(object sender,RoutedEventArgs e)=>SetSelectedRelationship("confirmed");
    private void SupersedeRelationship_Click(object sender,RoutedEventArgs e)=>SetSelectedRelationship("superseded");
    private void SetSelectedRelationship(string status){if(RelationshipsGrid.SelectedItem is not Relationship relationship){MessageBox.Show(this,"Select a relationship first.","Relationships");return;}if(status=="superseded"&&MessageBox.Show(this,"Mark this relationship as superseded? It will no longer be used for pathfinding.","Relationships",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return;_db.SetRelationshipStatus(relationship.Id,status);RefreshRelationships();}
    private void FindPath_Click(object sender,RoutedEventArgs e){if(Site is not{ } site||RelationshipDeviceBox.SelectedItem is not Device target){MessageBox.Show("Select a target device.");return;}var start=PathStartBox.Text.Trim();if(string.IsNullOrWhiteSpace(start)){MessageBox.Show("Enter a starting point.");return;}var tokens=UnavailableNodesBox.Text.Split(',',StringSplitOptions.TrimEntries|StringSplitOptions.RemoveEmptyEntries);var excludedNodes=new HashSet<string>(tokens.Where(x=>!x.StartsWith('#')),StringComparer.OrdinalIgnoreCase);var excludedHops=new HashSet<long>(tokens.Where(x=>x.StartsWith('#')).Select(x=>long.TryParse(x[1..],out var id)?id:0).Where(x=>x>0));var paths=_pathfinder.Find(_db.Relationships(site.Id),start,target.Name,excludedHops,excludedNodes);PathResultsList.ItemsSource=paths;if(paths.Count==0)MessageBox.Show(this,"No supported access path was found with the current exclusions.","Access paths");}
    private void BuildTopology_Click(object sender,RoutedEventArgs e)=>RenderTopology();
    private void TopologyOption_Changed(object sender,RoutedEventArgs e){if(_topology is not null)RenderTopology();}
    private void ClearTopologyTarget_Click(object sender,RoutedEventArgs e){TopologyTargetBox.SelectedItem=null;TopologyOnlyPathCheck.IsChecked=false;RenderTopology();}
    private void TopologyZoomOut_Click(object sender,RoutedEventArgs e){_topologyZoom=Math.Max(.45,_topologyZoom-.15);ApplyTopologyZoom();}
    private void TopologyZoomReset_Click(object sender,RoutedEventArgs e){_topologyZoom=1;ApplyTopologyZoom();}
    private void TopologyZoomIn_Click(object sender,RoutedEventArgs e){_topologyZoom=Math.Min(1.75,_topologyZoom+.15);ApplyTopologyZoom();}
    private void ApplyTopologyZoom(){TopologyScale.ScaleX=TopologyScale.ScaleY=_topologyZoom;}
    private void RenderTopology()
    {
        TopologyCanvas.Children.Clear();if(Site is not{ } site||TopologyRootBox.SelectedItem is not Device root){TopologySummaryText.Text="Select a site and starting firewall.";return;}var target=TopologyTargetBox.SelectedItem as Device;var map=_topology.Build(site.Id,root.Id,target?.Id,TopologyOnlyPathCheck.IsChecked==true);TopologySummaryText.Text=map.Summary;TopologyCanvas.Width=map.Width;TopologyCanvas.Height=map.Height;var nodes=map.Nodes.ToDictionary(x=>x.Device.Id);
        if(map.Nodes.Count==0){var empty=new TextBlock{Text=map.Summary,Foreground=Brush("#91A0B6"),FontSize=15,TextWrapping=TextWrapping.Wrap,Width=480};Canvas.SetLeft(empty,36);Canvas.SetTop(empty,40);TopologyCanvas.Children.Add(empty);return;}
        foreach(var edge in map.Edges)
        {
            if(!nodes.TryGetValue(edge.FromDeviceId,out var from)||!nodes.TryGetValue(edge.ToDeviceId,out var to))continue;var x1=from.X+103;var y1=from.Y+41;var x2=to.X+103;var y2=to.Y+41;var line=new System.Windows.Shapes.Line{X1=x1,Y1=y1,X2=x2,Y2=y2,Stroke=edge.IsOnSelectedPath?Brush("#4F8CFF"):Brush("#40516C"),StrokeThickness=edge.IsOnSelectedPath?3:1.5,ToolTip=$"{edge.RelationshipType.Replace('_',' ')}\nSource: {edge.Source}\nConfidence: {edge.Confidence:P0}\nStatus: {edge.Status}"};TopologyCanvas.Children.Add(line);var marker=new System.Windows.Shapes.Ellipse{Width=7,Height=7,Fill=edge.IsOnSelectedPath?Brush("#76A7FF"):Brush("#60738F"),IsHitTestVisible=false};Canvas.SetLeft(marker,x2-3.5);Canvas.SetTop(marker,y2-3.5);TopologyCanvas.Children.Add(marker);
            if(edge.IsOnSelectedPath||edge.RelationshipType!="CONNECTED_TO"){var label=new Border{Background=Brush("#111C2D"),BorderBrush=Brush("#2B3B53"),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(4),Padding=new Thickness(5,2,5,2),Child=new TextBlock{Text=edge.RelationshipType.Replace("_TO","").Replace('_',' '),Foreground=Brush("#91A0B6"),FontSize=9},IsHitTestVisible=false};Canvas.SetLeft(label,(x1+x2)/2-30);Canvas.SetTop(label,(y1+y2)/2-12);Panel.SetZIndex(label,1);TopologyCanvas.Children.Add(label);}
        }
        foreach(var node in map.Nodes)
        {
            var border=new Border{Width=206,Height=82,CornerRadius=new CornerRadius(9),Background=NodeBrush(node.Device.DeviceType),BorderBrush=node.IsRoot?Brush("#FFB74D"):node.IsTarget?Brush("#72E0C0"):node.IsOnSelectedPath?Brush("#4F8CFF"):Brush("#34445E"),BorderThickness=new Thickness(node.IsRoot||node.IsTarget?2.5:1.2),Padding=new Thickness(11,8,11,7),Cursor=System.Windows.Input.Cursors.Hand,ToolTip=$"{node.Device.Name}\nIP: {node.Device.IpAddress??"Not documented"}\nType: {node.Device.DeviceType??"Unknown"}\nZone: {node.Device.Zone??"Unknown"}"};var stack=new StackPanel();stack.Children.Add(new TextBlock{Text=(node.IsRoot?"◆ ":node.IsTarget?"● ":"")+node.Device.Name,FontWeight=FontWeights.SemiBold,FontSize=13,Foreground=Brush("#F2F6FC"),TextTrimming=TextTrimming.CharacterEllipsis});stack.Children.Add(new TextBlock{Text=node.Device.IpAddress??"IP not documented",Foreground=string.IsNullOrWhiteSpace(node.Device.IpAddress)?Brush("#718096"):Brush("#76A7FF"),FontFamily=new FontFamily("Cascadia Mono, Consolas"),FontSize=12,Margin=new Thickness(0,4,0,0)});stack.Children.Add(new TextBlock{Text=$"{node.Device.DeviceType??"Unknown type"}  ·  {node.Device.Zone??"No zone"}",Foreground=Brush("#91A0B6"),FontSize=10,Margin=new Thickness(0,3,0,0),TextTrimming=TextTrimming.CharacterEllipsis});border.Child=stack;border.MouseLeftButtonUp+=(_,_)=>{TopologyTargetBox.SelectedItem=_siteDevices.FirstOrDefault(x=>x.Id==node.Device.Id);RenderTopology();};Canvas.SetLeft(border,node.X);Canvas.SetTop(border,node.Y);Panel.SetZIndex(border,2);TopologyCanvas.Children.Add(border);
        }
        ApplyTopologyZoom();
    }
    private static Brush NodeBrush(string? type)=>type?.ToLowerInvariant() switch{"firewall"=>Brush("#40252D"),"router"=>Brush("#40331E"),"switch"=>Brush("#173659"),"hypervisor host"=>Brush("#153B36"),"server"=>Brush("#302650"),"virtual machine"=>Brush("#29284A"),_=>Brush("#182337")};
    private static Brush Brush(string color)=>new SolidColorBrush((Color)ColorConverter.ConvertFromString(color));
    private void AnalyzeTrouble_Click(object sender,RoutedEventArgs e)
    {
        if(Site is not{ } site){MessageBox.Show(this,"Select a site first.","Troubleshoot");return;}try{_relationshipInference.Infer(site.Id);var report=TroubleReportBox.Text.Trim();var plan=_troubleshooter.Analyze(site.Id,report,(TroubleTargetBox.SelectedItem as Device)?.Id);_activeTroubleSessionId=_db.SaveTroubleshootingPlan(site.Id,report,plan);TroubleSummaryText.Text=plan.Summary;TroubleStepsGrid.ItemsSource=_db.TroubleshootingSteps(_activeTroubleSessionId.Value);if(plan.Target is not null){TroubleTargetBox.SelectedItem=_siteDevices.FirstOrDefault(x=>x.Id==plan.Target.Id);_troubleUnavailableRelationships.Clear();RefreshTroubleTraversal(site,plan.Target);}TroubleSessionsGrid.ItemsSource=_db.TroubleshootingSessions(site.Id);}catch(Exception ex){MessageBox.Show(this,ex.Message,"Troubleshoot",MessageBoxButton.OK,MessageBoxImage.Information);}
    }
    private void TroubleSession_Changed(object sender,System.Windows.Controls.SelectionChangedEventArgs e){if(TroubleSessionsGrid.SelectedItem is not TroubleshootingSession session)return;_activeTroubleSessionId=session.Id;TroubleReportBox.Text=session.Description;TroubleSummaryText.Text=session.Summary;var target=_siteDevices.FirstOrDefault(x=>x.Id==session.TargetDeviceId);TroubleTargetBox.SelectedItem=target;TroubleStepsGrid.ItemsSource=_db.TroubleshootingSteps(session.Id);if(Site is{ } site&&target is not null){_troubleUnavailableRelationships.Clear();RefreshTroubleTraversal(site,target);}}
    private void TroublePending_Click(object sender,RoutedEventArgs e)=>SetTroubleStep("pending");
    private void TroubleCompleted_Click(object sender,RoutedEventArgs e)=>SetTroubleStep("completed");
    private void TroubleFailed_Click(object sender,RoutedEventArgs e)=>SetTroubleStep("failed");
    private void SetTroubleStep(string status){if(TroubleStepsGrid.SelectedItem is not TroubleshootingStep step){MessageBox.Show(this,"Select an investigation step first.","Troubleshoot");return;}_db.SetTroubleshootingStepStatus(step.Id,status);TroubleStepsGrid.ItemsSource=_db.TroubleshootingSteps(step.SessionId);if(Site is{ } site)TroubleSessionsGrid.ItemsSource=_db.TroubleshootingSessions(site.Id);}
    private void CommandSearch_Changed(object sender,System.Windows.Controls.TextChangedEventArgs e){if(_db is not null)CommandMemoryGrid.ItemsSource=_db.Commands(CommandSearchBox.Text);}
    private void RefreshTroubleTraversal(Site site,Device target){var trace=_traversal.Trace(site.Id,target.Id);TroubleTraversalGrid.ItemsSource=trace;var conflicts=trace.Count(x=>x.Status=="conflicting");TraversalSummaryText.Text=trace.Count==0?$"No device-to-host or device-to-network relationships are stored for {target.Name}. Re-import the source workbook or define relationships manually.":$"Trace outward from {target.Name}: {trace.Count} documented hop(s) across host, switch, subnet, VLAN and dependency boundaries"+(conflicts>0?$"; {conflicts} conflicting hop(s) require review.":".");var paths=_pathfinder.Find(_db.Relationships(site.Id),"Current workstation",target.Name,_troubleUnavailableRelationships);TraversalAccessPathText.Text=paths.Count==0?"No complete Current workstation → target access path is documented. The table still shows the diagnostic trace outward from the device.":string.Join("\n",paths.Take(2).Select(x=>x.Display.Split('\n')[0]));}
    private void ExcludeTraversalHop_Click(object sender,RoutedEventArgs e){if(Site is not{ } site||TroubleTargetBox.SelectedItem is not Device target||TroubleTraversalGrid.SelectedItem is not DiagnosticHop hop){MessageBox.Show(this,"Select a traversal hop first.","Device traversal");return;}_troubleUnavailableRelationships.Add(hop.RelationshipId);RefreshTroubleTraversal(site,target);}
    private void ResetTraversal_Click(object sender,RoutedEventArgs e){_troubleUnavailableRelationships.Clear();if(Site is{ } site&&TroubleTargetBox.SelectedItem is Device target)RefreshTroubleTraversal(site,target);}
    private void AddCommand_Click(object sender,RoutedEventArgs e){var dialog=new CommandDialog(){Owner=this};if(dialog.ShowDialog()!=true)return;_db.AddCommand(dialog.Platform,dialog.Category,dialog.CommandText,dialog.Purpose,dialog.RiskLevel,dialog.Notes);CommandMemoryGrid.ItemsSource=_db.Commands(CommandSearchBox.Text);}
    private void EditCommand_Click(object sender,RoutedEventArgs e){if(CommandMemoryGrid.SelectedItem is not CommandKnowledge selected){MessageBox.Show(this,"Select a command first.","Command memory");return;}var dialog=new CommandDialog(selected){Owner=this};if(dialog.ShowDialog()!=true)return;_db.UpdateCommand(selected with{Platform=dialog.Platform,Category=dialog.Category,CommandText=dialog.CommandText,Purpose=dialog.Purpose,RiskLevel=dialog.RiskLevel,Notes=dialog.Notes});CommandMemoryGrid.ItemsSource=_db.Commands(CommandSearchBox.Text);}
    private void CopyCommand_Click(object sender,RoutedEventArgs e){if(CommandMemoryGrid.SelectedItem is not CommandKnowledge selected){MessageBox.Show(this,"Select a command first.","Command memory");return;}Clipboard.SetText(selected.CommandText);}
    private void DeleteCommand_Click(object sender,RoutedEventArgs e){if(CommandMemoryGrid.SelectedItem is not CommandKnowledge selected){MessageBox.Show(this,"Select a command first.","Command memory");return;}if(MessageBox.Show(this,$"Remove this {selected.Platform} command from command memory?","Command memory",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return;_db.DeleteCommand(selected.Id);CommandMemoryGrid.ItemsSource=_db.Commands(CommandSearchBox.Text);}
    private void CompaniesList_SelectionChanged(object sender,System.Windows.Controls.SelectionChangedEventArgs e) { ReloadSites(); RefreshSite(); }
    private void SitesList_SelectionChanged(object sender,System.Windows.Controls.SelectionChangedEventArgs e)=>RefreshSite();
    private void AddCompany_Click(object sender,RoutedEventArgs e) { var d=new EditDialog("New company"){Owner=this}; if(d.ShowDialog()==true){var id=_db.AddCompany(d.Value);ReloadCompanies(id);} }
    private void EditCompany_Click(object sender,RoutedEventArgs e) { if(Company is not { } c)return; var d=new EditDialog("Edit company",c.Name){Owner=this};if(d.ShowDialog()==true){_db.RenameCompany(c.Id,d.Value);ReloadCompanies(c.Id);} }
    private void DeleteCompany_Click(object sender,RoutedEventArgs e) { if(Company is { } c&&MessageBox.Show($"Delete company '{c.Name}' and all its sites?","Confirm",MessageBoxButton.YesNo,MessageBoxImage.Warning)==MessageBoxResult.Yes){_db.DeleteCompany(c.Id);ReloadCompanies();} }
    private void AddSite_Click(object sender,RoutedEventArgs e) { if(Company is null){MessageBox.Show("Select or create a company first.");return;} var d=new EditDialog("New site",showAddress:true){Owner=this}; if(d.ShowDialog()==true){var id=_db.AddSite(Company.Id,d.Value,d.Address);ReloadSites(id);} }
    private void MergeSite_Click(object sender,RoutedEventArgs e)
    {
        if(Site is not { } source||Company is null){MessageBox.Show("Select the duplicate/source site first.");return;}var targets=_db.Sites(Company.Id).Where(x=>x.Id!=source.Id).ToList();var dialog=new MergeSiteDialog(source,targets){Owner=this};if(dialog.ShowDialog()!=true||dialog.Target is null)return;
        if(MessageBox.Show(this,$"Merge '{source.Name}' into '{dialog.Target.Name}'? This cannot be undone.","Confirm site merge",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return;
        try{_db.MergeSites(source.Id,dialog.Target.Id);ReloadSites(dialog.Target.Id);}catch(Exception ex){MessageBox.Show(this,$"The sites could not be merged. No partial changes were saved.\n\n{ex.Message}","Merge site",MessageBoxButton.OK,MessageBoxImage.Error);}
    }
    private void Edit_Click(object sender,RoutedEventArgs e) { if(Site is { } s){var d=new EditDialog("Edit site",s.Name,s.Address,true){Owner=this};if(d.ShowDialog()==true){_db.UpdateSite(s.Id,d.Value,d.Address);ReloadSites(s.Id);}} else if(Company is { } c){var d=new EditDialog("Edit company",c.Name){Owner=this};if(d.ShowDialog()==true){_db.RenameCompany(c.Id,d.Value);ReloadCompanies(c.Id);}} }
    private void Delete_Click(object sender,RoutedEventArgs e) { if(Site is { } s && MessageBox.Show($"Delete site '{s.Name}' and all its local data?","Confirm",MessageBoxButton.YesNo,MessageBoxImage.Warning)==MessageBoxResult.Yes){_db.DeleteSite(s.Id);ReloadSites();} else if(Site is null&&Company is { } c&&MessageBox.Show($"Delete company '{c.Name}' and all its sites?","Confirm",MessageBoxButton.YesNo,MessageBoxImage.Warning)==MessageBoxResult.Yes){_db.DeleteCompany(c.Id);ReloadCompanies();} }
    private void AddDevice_Click(object sender,RoutedEventArgs e){if(Site is not{ } site)return;var d=new DeviceDialog(){Owner=this};if(d.ShowDialog()==true){_db.AddDevice(site.Id,d.DeviceName,d.Ip,d.Mac,d.Serial,d.Vendor,d.Model,d.DeviceType,d.Zone,d.Description);RefreshSite();}}
    private void EditDevice_Click(object sender,RoutedEventArgs e){if(DevicesGrid.SelectedItem is not Device device){MessageBox.Show("Select a device first.");return;}var d=new DeviceDialog(device){Owner=this};if(d.ShowDialog()==true){_db.UpdateDevice(new Device(device.Id,device.SiteId,d.DeviceName,d.Ip,d.Mac,d.Serial,d.Vendor,d.Model,d.DeviceType,d.Zone,d.Description));RefreshSite();}}
    private void DeleteDevice_Click(object sender,RoutedEventArgs e){if(DevicesGrid.SelectedItem is not Device device){MessageBox.Show("Select a device first.");return;}if(MessageBox.Show(this,$"Delete device '{device.Name}' and its related facts, interfaces and topology relationships?","Confirm",MessageBoxButton.YesNo,MessageBoxImage.Warning)==MessageBoxResult.Yes){_db.DeleteDevice(device.Id);RefreshSite();}}
    private void AddNetwork_Click(object sender,RoutedEventArgs e){if(Site is not{ } site)return;var d=new NetworkDialog(){Owner=this};if(d.ShowDialog()==true){try{_db.AddNetwork(site.Id,d.NetworkName,d.Cidr,d.VlanId,d.Zone);RefreshSite();}catch(Exception ex){MessageBox.Show(this,$"Could not add network.\n\n{ex.Message}");}}}
    private void EditNetwork_Click(object sender,RoutedEventArgs e){if(NetworksGrid.SelectedItem is not NetworkRecord network){MessageBox.Show("Select a network first.");return;}var d=new NetworkDialog(network){Owner=this};if(d.ShowDialog()==true){try{_db.UpdateNetwork(new NetworkRecord(network.Id,network.SiteId,d.NetworkName,d.Cidr,d.VlanId,d.Zone));RefreshSite();}catch(Exception ex){MessageBox.Show(this,$"Could not update network.\n\n{ex.Message}");}}}
    private void DeleteNetwork_Click(object sender,RoutedEventArgs e){if(NetworksGrid.SelectedItem is not NetworkRecord network){MessageBox.Show("Select a network first.");return;}if(MessageBox.Show(this,$"Delete network '{network.Name}' ({network.Cidr})?","Confirm",MessageBoxButton.YesNo,MessageBoxImage.Warning)==MessageBoxResult.Yes){_db.DeleteNetwork(network.Id);RefreshSite();}}
    private void Upload_Click(object sender,RoutedEventArgs e)
    {
        if(Company is null){MessageBox.Show("Select or create the destination company first.");return;} var dialog=new OpenFileDialog{Filter="Supported files (*.csv;*.xlsx;*.vsdx)|*.csv;*.xlsx;*.vsdx|Visio (*.vsdx)|*.vsdx|CSV (*.csv)|*.csv|Excel (*.xlsx)|*.xlsx"}; if(dialog.ShowDialog()!=true)return;
        try
        {
            _pendingPath=dialog.FileName; _preview=[]; _visioPreview=[];
            if(_visioReader.Supports(dialog.FileName))
            {
                _visioPreview=_visioReader.Read(dialog.FileName).Proposals.ToList(); _visioImports.ClassifyForCompany(Company.Id,_visioPreview); PreviewGrid.ItemsSource=_visioPreview; ImportButton.IsEnabled=_visioPreview.Any(x=>x.Import);
                ImportStatus.Text=$"{_visioPreview.Count} proposal(s): {_visioPreview.Count(x=>x.Import)} selected; {_visioPreview.Count(x=>x.Status=="Unresolved site")} need a site mapping.";
            }
            else
            {
                _preview=_reader.Read(dialog.FileName).ToList(); if(_preview.Any(x=>!string.IsNullOrWhiteSpace(x.SiteLocation)))_imports.ClassifyForCompany(Company.Id,_preview); else if(Site is not null)_imports.Classify(Site.Id,_preview); else throw new InvalidDataException("The file has no Site Location column. Select a site before importing it."); PreviewGrid.ItemsSource=_preview; ImportButton.IsEnabled=_preview.Count>0; ImportStatus.Text=$"{_preview.Count} row(s) ready across {_preview.Select(x=>x.SiteLocation).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase).Count()} site(s).";
            }
            Tabs.SelectedIndex=3;
        }
        catch(Exception ex){MessageBox.Show(this,$"The file could not be read.\n\n{ex.Message}","Import",MessageBoxButton.OK,MessageBoxImage.Error);}
    }
    private void Import_Click(object sender,RoutedEventArgs e)
    {
        if(Company is null||_pendingPath is null)return;
        try
        {
            if(_visioPreview.Count>0){var touched=_visioImports.ImportForCompany(Company.Id,_pendingPath,_visioPreview);ReloadSites(Site?.Id??touched.FirstOrDefault()?.Id);}
            else {var siteAware=_preview.Any(x=>!string.IsNullOrWhiteSpace(x.SiteLocation));if(siteAware){var touched=_imports.ImportForCompany(Company.Id,_pendingPath,_preview);ReloadSites(Site?.Id??touched.FirstOrDefault()?.Id);}else if(Site is not null)_imports.Import(Site.Id,_pendingPath,_preview);else throw new InvalidOperationException("Select a site for this file.");}
            _preview=[];_visioPreview=[];_pendingPath=null;PreviewGrid.ItemsSource=null;ImportButton.IsEnabled=false;ImportStatus.Text="Import complete.";RefreshSite();
        }
        catch(Exception ex){MessageBox.Show(this,$"Import failed.\n\n{ex.Message}","Import",MessageBoxButton.OK,MessageBoxImage.Error);}
    }
    private Conflict? SelectedConflict()=>ConflictsGrid.SelectedItem as Conflict;
    private void Resolve(Resolution resolution,string? manual=null) { var c=SelectedConflict();if(c is null||c.Status!="unresolved"){MessageBox.Show("Select an unresolved conflict first.");return;}if(resolution==Resolution.Manual&&string.IsNullOrWhiteSpace(manual)){MessageBox.Show("Enter the correct value first.");return;}_imports.Resolve(c,resolution,manual);RefreshSite(); }
    private void Keep_Click(object sender,RoutedEventArgs e)=>Resolve(Resolution.KeepExisting);
    private void Accept_Click(object sender,RoutedEventArgs e)=>Resolve(Resolution.AcceptNew);
    private void Manual_Click(object sender,RoutedEventArgs e)=>Resolve(Resolution.Manual,ManualValue.Text.Trim());
    private void Separate_Click(object sender,RoutedEventArgs e)=>Resolve(Resolution.SeparateDevice);
}
